### ISSUE TITLE
Request!

### ISSUE THREAD

**Issue by EternalEmrys** [CCBlueX/LiquidBounce-1.12.2#2]
I'd like to become a dev for liquid bounce I could easily get the versions to all updated, to like, 1.9, 1.10, 1.11, 1.11.2, so on and so forth, like 1.12 and 1.12.2, I'm an experienced dev, I helped make the client "Xdolf" and the skid of Xdolf names "Xulu". Please consider. Thank you.

**Comment by Marco-MC** [comment]
no
